version: "3"
services:
  multitenant-db:
    image: "postgres:latest"
    container_name: "multitenant-db"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./multitenant-db-data:/var/lib/postgresql/data
